# Generated by Django 2.0 on 2019-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingItem',
        ),
    ]
